# 3 - Tipos e Conversão de tipos
O Numpy suporta uma variedade de tipos muito maior do que o Python.

Existem 5 tipos básicos numéricos
- Booleans (bool)
- Integers (int)
- Unsigned Intergers (uint)
- Floating Points (float)
- Complex

Complementarmente, a célula abaixo mostra um quadro comparativos com uma maior quantidade de tipos do Numpy.

In [ ]:
import numpy as np

x recebe 1.0 como um float de 32 bits.

In [ ]:
x = np.float32(1.0)
x

2

y recebe um array de inteiros.

In [ ]:
y = np.int_([1,2,4])
y

array([1, 2, 4])

Foi especificado apenas o valor de parada, então os valores gerados serão de 0 a 3, inteiros sem sinal de 8 bits.

In [ ]:
z = np.arange(3, dtype=np.uint8)
z

array([0, 1, 2], dtype=uint8)

Converte uma lista de três elementos inteiros para um array de três elementos do tipo float.

In [ ]:
np.array([1, 2, 3], dtype='f')

array([1., 2., 3.], dtype=float32)

## Convertendo tipos de arrays

Para convertermos arrays Numpy, basta utilizarmos o método astype().

Converte z para um array do tipo float.

In [ ]:
z.astype(float)

array([0., 1., 2.])

Converte o array z para tipo inteiro de 8 bits.

In [ ]:
np.int8(z)

array([0, 1, 2], dtype=int8)

Para verificarmos o tipo de um array Numpy, basta verificarmos o seu atributo dtype.

In [ ]:
z.dtype

dtype('uint8')