# 7 - Filtragem de dados
Filtragem de dados é uma tarefa importantíssima na vida de qualquer cientista de dados. Nessa seção, veremos como criar filtros em um conjunto de dados utilizando o Pandas.

## Operadores booleanos

### and

Retorna true se x for maior que 5 e menor que 15.

In [ ]:
x = 12

In [ ]:
x > 5 and x < 15

True

### or

Retorna true se y for menor que 7 ou maior que 13.

In [ ]:
y = 5

In [ ]:
y < 7 or y > 13

True

### not

Nega a expressão.

In [ ]:
not True

False

In [ ]:
not False

True

### Numpy

In [ ]:
import numpy as np

np_height = np.array([1.73, 1.68, 1.71, 1.89, 1.79])
np_weight = np.array([65.4, 59.2, 63.6, 88.4, 68.7])
bmi = np_weight / np_height ** 2

bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

Para cada elemento do array retorna true se ele for mais que 21 e false se for menor ou igual a 21.

In [ ]:
bmi > 21

array([ True, False,  True,  True,  True])

In [ ]:
bmi > 21 and bmi < 22

ValueError: ignored

Para todos os elementos do array, retorna true se o valor for entre 21 e 22.

In [ ]:
np.logical_and(bmi > 21, bmi < 22)

array([ True, False,  True, False,  True])

Retorna apenas os valores que estão entre 21 e 22 no array.

In [ ]:
bmi[np.logical_and(bmi > 21, bmi < 22)]

array([21.85171573, 21.75028214, 21.44127836])

## Filtrando um DataFrame Pandas

In [ ]:
import pandas as pd
brics = pd.read_csv('brics.csv', index_col=0)
brics

**Objetivo**: selecionar os países com área maior do que 8 milhões de km2

3 passos:
- Selecionar a coluna "area"
- Fazer uma comparação na coluna "area"
- Usar o resultado para selecionar os países

In [ ]:
# Selecionar a coluna "area"
brics['area']

In [ ]:
# Fazer uma comparação na coluna "area"
brics['area'] > 8
is_huge = brics['area'] > 8
is_huge

In [ ]:
# Usar o resultado para selecionar os países
brics[is_huge]

Ler um arquivo csv.

In [3]:
# Importando dataset de carros
import pandas as pd
cars = pd.read_csv('cars.csv', index_col = 0)
cars

cars_per_cap        country  drives_right
US            809  United States          True
AUS           731      Australia         False
JAP           588          Japan         False
IN             18          India         False
RU            200         Russia          True
MOR            70        Morocco          True
EG             45          Egypt          True

Seleciona uma coluna específica e cria um subconjunto apenas com os dados dessa coluna.

In [ ]:
# Extraia a coluna 'drives_right' do DataFrame 'cars' e atribua a variável 'dr'
dr = cars['drives_right']

# Use a variável 'dr' para criar um subconjunto de dados chamado 'sel'
sel = cars[dr]

# Imprima a variável 'sel'
print(sel)

Car_maniac recebe apenas as linhas que possuirem valores na coluna cpc maiores que 500.

In [4]:
# Crie uma variável car_maniac: linhas que possuem 'cars_per_cap' maiores do que 500
cpc = cars['cars_per_cap']
many_cars = cpc > 500
car_maniac = cars[many_cars]

# Imprima 'car_maniac'
print(car_maniac)

     cars_per_cap        country  drives_right
US            809  United States          True
AUS           731      Australia         False
JAP           588          Japan         False


Retorna apenas as linhas onde a coluna cpc possui valor entre 100 e 500.

In [5]:
# Importe o conjunto de dados 'cars.csv', bem como as bibliotecas 'pandas' e 'numpy'
import pandas as pd
import numpy as np
cars = pd.read_csv('cars.csv', index_col = 0)

# Crie a variável 'medium': linhas que possuem 'cars_per_cap' entre 100 e 500
cpc = cars['cars_per_cap']
between = np.logical_and(cpc > 100, cpc < 500)
medium = cars[between]

# Imprima 'medium'
print(medium)

    cars_per_cap country  drives_right
RU           200  Russia          True
